### ISSUE TITLE
Events ACL does not grant permissions (403 error)

### ISSUE THREAD

**Issue by juresaht2** [rundeck/rundeck#6459]
**Describe the bug**
Setting up a non-admin user with an ACL like:
```
    - equals:
        kind: event
      allow: [read] # allow reading activity logs
```
...does not give the user permission to access the activity logs. 

**My Rundeck detail**
* Rundeck version: 3.3.2
* install type: rpm
* OS Name/version: CentOS 8

**To Reproduce**
1. Set up project with ACL
```
for:
  resource:
    - equals:
        kind: job
      allow: [read, run, kill]
    - equals:
        kind: node
      allow: [read]
    - equals:
        kind: event
      allow: [read] # allow reading activity logs
  job:
    - allow: [read,run,kill]
  node:
    - allow: [read,run] # allow read/run for nodes 
description: "ad"
by:
  group: rundeck_group
```
2. Set up user with access to the project, without admin permissions (in global ACL), add to group, etc
3. Log in and see 403 error trying to access activity logs. Clicking the activity log explicitly, the user is informed that they do not have permission.

**Expected behavior**
I expected read permissions to the activity logs to be granted with this ACL.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 85

**Additional context**
I am using AD auth, but I do not believe this is relevant

**Comment by fgutierrezz** [comment]
Hello

Could you capture the "audit. Log" output while you reproduce the issue

Thanks
Felipe

**Comment by juresaht2** [comment]
Hello,

Find the rundeck.audit.log here:
https://pisarna.t-2.com/s/zHQZgNd6E2xzB4n

It's the log created from signing in with my user (jsah) visiting the Jobs page for project "Interno" where "An Error Occurred: Request failed with status code 403" is displayed, then visiting the Activity page directly, where "Not authorized to read Events in project Interno" is displayed. The group names correspond to the projects.

**Comment by arturmartins** [comment]
I'm also experiencing the same. Same version.

**Comment by arturmartins** [comment]
I have the following `Stored System ACL policy`:

```
description: Ateam, read-only access.
context:
  application: 'rundeck'
by:
  group: ['Ateam']
for:
  resource:
    - equals:
        kind: system
      allow: [read] 
    - equals:
        kind: system_acl
      allow: [read] 
  project:
    - match:
        name: '.*'
      allow: [read]

  storage:
    - allow: [read]
```

and the following project ACL Policy:

```
description: Project1 Policy 
by:
    group: ['Ateam']
for:
  resource:
    - allow: read
    - equals:
        kind: job
      allow: [read, view, run, kill]
    - equals:
        kind: node
      allow: [read,refresh]
    - equals:
        kind: event
      allow: [read]
  job:
    - allow: [run,view,read,kill]
  node:
    - allow: [read,run]
```

All the users of Ateam are able to see the events, but only if they are logged in rundeck at the time that I save the system policy. 

The problem happens when the user does the logout and login. After that, the user can't see any event again. The way I can restore the access is by opening the Stored System ACL policy, add a new blank line and save it.

**Comment by arturmartins** [comment]
ok, I solved the issue by deleting both policies and move them to a single file in /etc/rundeck/ateam.aclpolicy. All works now.

My setup is very simple: fresh rundeck install with only admin and apitoken policy. Looks like there is a bug in the ACL precedence logic?

**Comment by cesouza-br** [comment]
I'm also experiencing the same.

My Rundeck detail

Rundeck version: 3.3.4
install type: rpm
OS Name/version: CentOS 8

**Comment by MegaDrive68k** [comment]
I reproduced the issue in this way:

Using this System ACL (Gear Icon > Access Control):

```yaml
description: app level.
context:
  application: 'rundeck'
for:
  resource:
    - equals:
        kind: system
      allow: [read] 
    - equals:
        kind: system_acl
      allow: [read] 
  project:
    - match:
        name: '.*'
      allow: [read]

  storage:
    - allow: [read]
by:
  group: user
```

And this inside the project (Project Settings > Access Control):

```yaml
description: project level.
for:
  resource:
    - equals:
        kind: job
      allow: [read, run, kill]
    - equals:
        kind: node
      allow: [read]
    - equals:
        kind: event
      allow: [read]
  job:
    - allow: [read,run,kill]
  node:
    - allow: [read,run] 
by:
  group: user
```

I obtain the 403 error:

![Screenshot_1](https://user-images.githubusercontent.com/51376003/95617319-a017d300-0a41-11eb-8934-6a77e98200f2.png)

![Screenshot_2](https://user-images.githubusercontent.com/51376003/95617341-a443f080-0a41-11eb-9f31-e06e9a603531.png)

But using both ACL definitions in the same policy (Gear Icon > Access Control) works:

```yaml
description: project level.
context:
  project: '.*'
for:
  resource:
    - equals:
        kind: job
      allow: [read, run, kill]
    - equals:
        kind: node
      allow: [read]
    - equals:
        kind: event
      allow: [read]
  job:
    - allow: [read,run,kill]
  node:
    - allow: [read,run] 
by:
  group: user

---

description: app level.
context:
  application: 'rundeck'
for:
  resource:
    - equals:
        kind: system
      allow: [read] 
    - equals:
        kind: system_acl
      allow: [read] 
  project:
    - match:
        name: '.*'
      allow: [read]

  storage:
    - allow: [read]
by:
  group: user
```

![Screenshot_3](https://user-images.githubusercontent.com/51376003/95617741-46fc6f00-0a42-11eb-8975-110c44fe3f39.png)

![Screenshot_4](https://user-images.githubusercontent.com/51376003/95617751-4c59b980-0a42-11eb-88aa-3751567332b6.png)

**Comment by lmn-sre** [comment]
Same here after the latest upgrade to 3.3.4 :-(

My Rundeck detail

Rundeck version: 3.3.4
install type: rpm
OS Name/version: CentOS 7

**Comment by cesouza-br** [comment]
Thank you Reiner. It's working.

**Comment by cezary-zemis-kendaxa** [comment]
Confirm this issue in 3.3.5. I have just upgraded from 3.3.1 where I have not observed it.

**Comment by juresaht2** [comment]
I've just upgraded to 3.3.7 and the issue appears to have been fixed.

**Comment by juresaht2** [comment]
Ah... hm. Log out and log in and the issue is here once more.

**Comment by cuipito** [comment]
Does anybody know if this bug is also in the enterprise edition?
  
The bug is here quite some time and is its quite frustrating to deal with, i could maybe convince some people to buy the Enterprise edition if this bug is not there.

**Comment by tseeker** [comment]
Still having the same issue on 3.3.8. Sometimes it seems to go away because saving the ACLs seems to affect the results, but logging out then back in changes the situation... sometimes.

**Comment by Z3r0Sum** [comment]
Can confirm as well - Rundeck version 3.3.5.  We had to stack our project ACLs onto system in order to avoid the problem.

**Comment by hs-hub-world** [comment]
Same issue here with BUILD : 3.3.8-20210111

One thing came to mind this may or may not be related, is the ACL case insensitive with user name -? Because I have noticed when a user logs-in very first time into Rundeck the username is logged in the Summary page based on their initial username entry (example User1 vs user1 vs UsEr1 vs uSer1), so if Rundeck is checking the user ACL and if it's case sensitive how will it know which username to compare with the ACL -?
we use LDAP /Active Directory
- We have ACL in the project and in the System.
- Event permission is assigned at both locations with full access


![image](https://user-images.githubusercontent.com/20629911/106816602-786cfc00-662a-11eb-9f7f-50991be5af72.png)


![image](https://user-images.githubusercontent.com/20629911/106816744-ab16f480-662a-11eb-9cdf-add73396ef65.png)

**Comment by jbanda15** [comment]
I have a customer with the same issue. 
The advice in this link helps me a lot. [https://github.com/rundeck/rundeck/issues/6459#issuecomment-706331806](url) 
Thanks, @MegaDrive68k

**Comment by niphlod** [comment]
+1 for the request to fix this... is there an ETA ?

**Comment by pkgoncalvesbefore** [comment]
Same issue here. I'm running RunDeck Community 3.3.10.
